### ISSUE TITLE
General UI bugs

### ISSUE THREAD

**Issue by pwalsh** [openspending/os-packager#22]
# Tasks

* [ ] On latest Safari, when scrolling right on the sample CSV table when a horizontal scroll is in effect, it is not possible to scroll back left

**Comment by kravets-levko** [comment]
@pwalsh I tried to reproduce this bug in Safari 9.0, but it didn't reproduce. Can you provide more info? Thanks.

**Comment by pwalsh** [comment]
@kravets-levko ok, we'll come back to it after design.

**Comment by pwalsh** [comment]
FIXED.
