### ISSUE TITLE
Documentation for how to use the output datapackage.json

### ISSUE THREAD

**Issue by danfowler** [openspending/os-packager#32]
The specification of [Data Packages](http://dataprotocols.org/data-packages/index.html) means that a `datapackage.json` `MUST` live in a directory with the data uploaded in Step 1.  Maybe a small amount of text on the Step 4 page that specifies where to save the `datapackage.json` is necessary.

cc: @cecilaki

**Comment by cecilaki** [comment]
Also, what about naming this datapackage something like "my-dataset-datapackage.json" ?

**Comment by pwalsh** [comment]
@cecilaki data packages must be called `datapackage.json`

@danfowler not necessarily, no. if the CSV added was by URL, then, there is no need for co-location. Surely docs will be good here, but the docs will be different for:

1. The standalone fiscal data packager
2. The integration of this code into the whole OpenSpending Next import flow.

So, not sure how we can act on this right now.

**Comment by pwalsh** [comment]
WONTFIX.
