### ISSUE TITLE
Add environment variable for the API-Key

### ISSUE THREAD

**Issue by akariv** [openspending/os-packager#52]
Currently the API Key is hard-coded to 'openspending-next'.

For production we need to be able to extract it from an environment variable at runtime (let's name it `OS_CONDUCTOR_API_KEY`)

**Comment by pwalsh** [comment]
@akariv API Key will be populated from the user identity object, and is not a key for the service itself. The current key is a "fake user" just so we could get things rolling until we have the identity service and https://github.com/openspending/os-packager/issues/50

**Comment by akariv** [comment]
understood - closing.
