### ISSUE TITLE
Cosmopolitan API don't fetch the entire dataset

### ISSUE THREAD

**Issue by akariv** [openspending/os-packager#56]
Some datasets have more that 100 data items, however API calls return only 100 (with url for the next page). 

I guess a short term solution could be to raise the page size for currencies and countries to a more reasonable size (I don't expect the number of either to change drastically in the near future). As for other datasets, further consideration might be necessary.

**Comment by kravets-levko** [comment]
PR https://github.com/openspending/os-packager/pull/57
