### ISSUE TITLE
Validate the model also after providing meta-data

### ISSUE THREAD

**Issue by akariv** [openspending/os-packager#59]
Make sure that we verify the model with the FDP schema after filling the metadata (between steps 3 and 4). 
This will help us catch bugs related to meta-data incompatible with the official schema.

**Comment by pwalsh** [comment]
duplicates https://github.com/openspending/os-packager/issues/53

**Comment by akariv** [comment]
@pwalsh not really duplicates - this issue is for validating the model (i.e. datapackage.json), not the CSV file.

**Comment by pwalsh** [comment]
Ah right. I thought that was already happening.

**Comment by pwalsh** [comment]
https://github.com/openspending/openspending/issues/868
