### ISSUE TITLE
CSV dialect should be added to datapackage.json according to spec

### ISSUE THREAD

**Issue by akariv** [openspending/os-packager#66]
Make sure that we take the dialect (as papaparse detects it) and record it in the output datapackage.json.

**Comment by akariv** [comment]
See discussion here: https://github.com/openspending/openspending/issues/859

**Comment by pwalsh** [comment]
It is actually a different spec.

**Comment by pwalsh** [comment]
https://github.com/openspending/openspending/issues/866
